### ISSUE TITLE
Feature: Improved error handling in YAML syntax

### ISSUE THREAD

**Issue by blackandred** [riotkit-org/riotkit-do#45]
**Problem to solve:** Handling failed steps
**Proposed solution:** "finally_steps" attribute next to "steps". Finally steps could execute all the time
**Other solution to consider:** In commandline introduce a symbol to mark tasks that should execute always regardless of result of previous tasks

**Comment by blackandred** [comment]
What about this? To consider.

```
steps:
            - "mkdir -p"
            - catch: "%RKD% :slack"
            - catch_all: "..."
            - finally: "%RKD% :cleanup"
```
